app:
  name: "article_hub"

server:
  port: 8000

database:
  username: root
  password: root
  port: 3306
  host: localhost
  dbname: database_name
  sslmode: disable
  parsetime: true

jwt:
  secret: secret_word
  expiration: 604800